export type GuideCategory = 'Grammar' | 'Loanwords' | 'Phrases' | 'Conjugations';

export interface SectionImage {
	/** Path under public/, e.g. '/images/ser-vs-estar-diagram.svg'. */
	src: string;
	/** Describes what the image shows. */
	alt: string;
	/** Attribution + license, supports markdown links. Omit only for self-made diagrams. */
	credit?: string;
}

export interface GuideSection {
	heading: string;
	body: string[];
	/** Optional in-body image, rendered after this section's paragraphs. */
	image?: SectionImage;
}

export interface FaqItem {
	question: string;
	answer: string;
}

export interface Source {
	label: string;
	url: string;
}

/**
 * Surfaced as a callout near the top of the page. Exists mainly for slang/loanword
 * entries where register and regional variation ARE the answer, not a footnote —
 * see CLAUDE.md section 6 ("俚语与文化敏感内容的处理"). Optional everywhere else.
 */
export interface UsageNote {
	register?: 'neutral' | 'casual' | 'informal' | 'formal' | 'vulgar' | 'offensive';
	/** e.g. "Playful/affectionate in Mexico; can read as an insult in Spain." */
	regionNote?: string;
}

export interface ConjugationForm {
	/** e.g. "yo", "tú", "je", "ich" */
	pronoun: string;
	form: string;
}

export interface ConjugationTense {
	/** e.g. "Present", "Preterite", "Imperfect", "Future", "Conditional", "Subjunctive (present)" */
	tense: string;
	forms: ConjugationForm[];
}

/**
 * Generated by `tools/conjugate.mjs` — regular verbs via the ending-rule functions,
 * irregular verbs from the hand-verified IRREGULAR_VERBS table in that file. See the
 * module docstring there for why this must never be typed in from memory.
 */
export interface ConjugationTable {
	/** Infinitive, e.g. "ser". */
	verb: string;
	language: string;
	translation: string;
	regularity: 'regular' | 'irregular' | 'stem-changing';
	tenses: ConjugationTense[];
	/** The authoritative grammar source the table was checked against. */
	source: Source & { note?: string };
}

export interface Guide {
	slug: string;
	category: GuideCategory;
	title: string;
	description: string;
	/** Original publication date. Falls back to `updated` when unset, so only articles that have since been edited need it. */
	published?: string;
	updated: string;
	/** One or two sentences summarizing the core finding/argument, surfaced above the fold for GEO/AI-search extraction. */
	coreSummary: string;
	/** Primary target/source language this entry is about, e.g. "Spanish". Omit for entries that aren't language-specific (rare). */
	language?: string;
	usageNote?: UsageNote;
	conjugation?: ConjugationTable;
	sections: GuideSection[];
	faq?: FaqItem[];
	sources?: Source[];
	/** Path under public/, e.g. '/images/slug.jpg'. Falls back to /favicon.svg when unset. */
	image?: string;
	/** Describes what the photo shows. Falls back to the article title when unset. */
	imageAlt?: string;
	/** Attribution text, supports markdown links like body/FAQ text. */
	imageCredit?: string;
}

export const guides: Guide[] = [
	{
		slug: 'por-vs-para',
		category: 'Grammar',
		title: 'Por vs. Para: The Actual Difference (With Real Examples)',
		description: 'Por and para both translate as "for," which is exactly why English speakers mix them up. The real rule has nothing to do with translation.',
		published: '2026-08-03',
		updated: '2026-08-04',
		coreSummary: 'Para marks purpose, destination, deadline, or recipient: the thing an action is aimed at. Por marks cause, means, duration, exchange, or motion through a place: the thing an action moves through or comes from. Both can translate as English "for," which is exactly why the English translation is the wrong tool for choosing between them.',
		language: 'Spanish',
		sections: [
			{
				heading: 'Why one English word hides two Spanish prepositions',
				body: [
					'English collapses a lot of ground into the single word "for": *this gift is for you*, *I studied for two hours*, *thanks for the help*, *we left for Madrid*. Spanish keeps two separate prepositions for that ground, and they are not interchangeable. Using the wrong one is a genuine grammar error, not a stylistic slip, and Spanish speakers notice it immediately.',
					'The reason English speakers default to translating word-for-word is that "for" does not map cleanly onto either *por* or *para* on its own. The fix is to stop translating and start asking what role the phrase is playing: is it pointing at a goal, or is it pointing at a cause? *Para* points forward, at where something is headed. *Por* points backward or sideways, at why or how or through what something happens.',
				],
			},
			{
				heading: 'Para: purpose, destination, deadline, recipient',
				body: [
					'*Para* answers "what for?" or "where to?" It always has a target. Four uses cover almost everything you will see:',
					'**Purpose or goal.** *Estudio español para viajar a Chile el próximo año.* (I study Spanish in order to travel to Chile next year.) If you can rephrase the sentence with "in order to," it is *para*.',
					'**Destination.** *Salimos para Madrid mañana.* (We\'re leaving for Madrid tomorrow.) The endpoint of the trip, not the road you take to get there.',
					'**Deadline.** *El informe es para el viernes.* (The report is due by Friday.) A point in the future the action is aimed at, not a stretch of time it fills.',
					'**Recipient.** *Este regalo es para mi abuela.* (This gift is for my grandmother.) Who the thing is ultimately meant for.',
				],
				image: {
					src: '/images/por-vs-para-diagram.svg',
					alt: 'Two-column comparison diagram: POR covers cause, means, duration, exchange, and motion through; PARA covers purpose, destination, deadline, and recipient, each with a short Spanish example sentence.',
				},
			},
			{
				heading: 'Por: cause, means, duration, exchange, motion through',
				body: [
					'*Por* answers "why?" or "how?" or "through what?" It points at an origin, a method, or a path, not a destination.',
					'**Cause or reason.** *Cerraron la escuela por la tormenta.* (They closed the school because of the storm.) This is the one learners get wrong most often in the other direction: *gracias por tu ayuda* ("thanks for your help") uses *por*, not *para*, because the help is the reason for the thanks, not its destination.',
					'**Means.** *Te llamo por teléfono esta noche.* (I\'ll call you by phone tonight.) The channel something travels through.',
					'**Duration.** *Vivimos en Lima por tres años.* (We lived in Lima for three years.) A stretch of time the action fills, not a deadline it\'s aimed at (compare this to *el informe es para el viernes* above).',
					'**Exchange.** *Cambié mi coche viejo por uno nuevo.* (I traded my old car for a new one.) Money or goods changing hands, one thing standing in for another.',
					'**Motion through a place.** *Caminamos por el centro histórico.* (We walked through the historic center.) Contrast this with *para*\'s destination sense: *caminamos para el centro* would mean walking toward downtown as a goal, not wandering through it.',
				],
			},
			{
				heading: 'A test that actually works, and the phrases where it breaks',
				body: [
					'Because the categories above can blur together in a fast conversation, the fastest working test is a rephrasing test, not a translation test: if you can substitute "in order to," "for the purpose of," or "by [deadline]" and the sentence still makes sense, it\'s *para*. If you can substitute "because of," "by means of," "through," or "in exchange for," it\'s *por*.',
					'A handful of set phrases don\'t map onto either category cleanly and are just worth memorizing directly: *por fin* (finally), *por supuesto* (of course), *por ejemplo* (for example), and *para siempre* (forever) are fixed expressions where the preposition is baked into the idiom rather than derived from the rule.',
					'Por and para aren\'t the only pair of Spanish words that collapse into one option in English: [ser and estar](/ser-vs-estar/) both translate as "to be," and the logic for telling them apart works the same way this one does. Stop translating, and ask what job the word is doing in the sentence.',
				],
			},
			{
				heading: '"Estar para" and "estar por": one more place they split',
				body: [
					'The two prepositions split again when they pair with *estar*, and here the two phrases genuinely overlap rather than sitting in clean, separate categories. *Estar para* + infinitive most often signals readiness or mood: *No estoy para chistes* ("I\'m not in the mood for jokes") uses it to describe a state of mind, and the same construction can describe something poised and ready to happen. *Estar por* + infinitive leans toward intention or something expected in the near future, closer to "about to" or "still to be done."',
					'Both phrases can genuinely mean "about to" depending on the region, which makes this one of the few spots where the clean por/para logic above gives way to dialect variation: some Spanish-speaking regions favor *estar por* for "about to," others reach for *estar para* in the same situation. Unlike the core rule, this is a case where listening to how the people around you actually talk is more reliable than applying a fixed rule.',
				],
			},
		],
		faq: [
			{
				question: 'Do you say "gracias por" or "gracias para"?',
				answer: '"Gracias por," always. Thanks are given for a reason or cause (someone\'s help, a favor, a gift already received), which is *por* territory. "Gracias para" is a common learner error precisely because "for" sounds neutral in English but the underlying logic is causal, not purpose-directed.',
			},
			{
				question: 'Is there a quick test for choosing por or para?',
				answer: 'Try substituting the English phrase. If "in order to" or "by [a deadline]" fits, use *para*. If "because of," "through," "by means of," or "in exchange for" fits, use *por*. It fails on a small set of fixed idioms (like *para siempre*, "forever"), which are worth memorizing as exceptions rather than derived from the rule.',
			},
			{
				question: 'Why does "por el parque" mean something different from "para el parque"?',
				answer: '*Caminamos por el parque* means walking through the park: the park is the path, not the goal. *Caminamos para el parque* means walking toward the park as a destination. Same verb, same object, opposite relationship between the walker and the place.',
			},
			{
				question: 'Does the por/para distinction disappear in casual speech?',
				answer: 'No. Unlike some formal-register rules that loosen in everyday conversation, native speakers keep por and para distinct in all registers, from text messages to formal writing. Mixing them up is one of the most reliable ways a sentence reads as non-native, even when every other word is correct.',
			},
		],
		sources: [
			{ label: 'Real Academia Española — El buen uso del español: "Las preposiciones por y para"', url: 'https://www.rae.es/buen-uso-espa%C3%B1ol/las-preposiciones-por-y-para' },
			{ label: 'Spanish Academy — "What\'s the Difference Between \'Estar Por\' and \'Estar Para\'?"', url: 'https://www.spanish.academy/blog/whats-the-difference-between-estar-por-and-estar-para/' },
		],
	},
	{
		slug: 'ser-vs-estar',
		category: 'Grammar',
		title: 'Ser vs. Estar: How to Actually Tell Them Apart',
		description: 'Both mean "to be," which is why English speakers struggle with them. The real distinction is defining a trait versus describing a state.',
		published: '2026-08-03',
		updated: '2026-08-03',
		coreSummary: 'Ser identifies and defines: identity, origin, inherent characteristics, time, and material. Estar locates and describes a state: location, condition, and the result of a change. The common shorthand "ser is permanent, estar is temporary" breaks down often enough (someone can be permanently dead and use estar, or be only briefly a student and use ser) that it\'s more reliable to ask whether the sentence is defining the subject or reporting its current condition.',
		language: 'Spanish',
		usageNote: {
			regionNote: 'This distinction is standard across every variety of Spanish — Spain, Mexico, and the rest of Latin America all draw the ser/estar line the same way. What varies regionally is which adjectives get treated as "characteristics" vs. "states" in edge cases (see the FAQ on ser/estar with adjectives), not the underlying rule.',
		},
		sections: [
			{
				heading: 'One English verb, two Spanish jobs',
				body: [
					'English "to be" does double duty: it identifies things (*she is a doctor*) and it describes their state (*she is tired*). Spanish splits that job between two verbs that are not interchangeable. Using the wrong one doesn\'t just sound foreign — it can genuinely change what a sentence means, which is different from most por/para-style mix-ups where the error is purely grammatical.',
					'The textbook shorthand is "ser for permanent, estar for temporary," and it gets learners most of the way there. But it has real exceptions: *está muerto* ("he is dead") uses estar for something about as permanent as it gets, and *fue profesor por dos años* ("he was a teacher for two years") uses ser for something clearly temporary. The more reliable question is: is this sentence defining what the subject fundamentally is, or reporting a state it currently happens to be in?',
				],
			},
			{
				heading: 'Ser: identity, origin, and defining traits',
				body: [
					'**Identity and origin.** *Es de Colombia. Soy profesor.* (She is from Colombia. I am a teacher.) Where someone or something is from, and what category it belongs to.',
					'**Inherent characteristics.** *Ella es simpática.* (She is nice — as a trait of who she is.) This is the sentence Spanish teachers use most often to introduce the contrast, because swapping in estar here doesn\'t just sound wrong, it changes the claim being made (see the next section).',
					'**Time, dates, and where events happen.** *Son las tres. La fiesta es aquí.* (It\'s three o\'clock. The party is here.) Note that last one: the location of an *event* uses ser, while the location of a physical *object or person* uses estar — a distinction that trips up a lot of learners because both look like "location" sentences on the surface.',
					'**Material and possession.** *La mesa es de madera. El libro es de Ana.* (The table is made of wood. The book belongs to Ana.) What something is made of or who it belongs to is treated as a defining fact, not a state.',
				],
				image: {
					src: '/images/ser-vs-estar-diagram.svg',
					alt: 'Two-column comparison diagram: SER covers identity/origin, inherent characteristics, time/date/events, and material/possession; ESTAR covers location, temporary condition, result of a change, and ongoing action, each with a short Spanish example.',
				},
			},
			{
				heading: 'Estar: location, condition, and the result of a change',
				body: [
					'**Location of people, places, and objects.** *Madrid está en España. El libro está en la mesa.* (Madrid is in Spain. The book is on the table.) Physical location — where something or someone actually is right now — is estar\'s territory almost without exception.',
					'**Temporary or perceived condition.** *Ella está simpática hoy.* (She\'s being nice today.) This is the direct contrast with *ella es simpática* above: swapping ser for estar with the same adjective doesn\'t just change the tense feel, it changes the claim from "this is who she is" to "this is how she\'s acting right now" — implying it might not usually be the case.',
					'**The result of a change.** *La puerta está abierta.* (The door is open.) Someone opened it; estar reports the resulting state, not the identity of the door.',
					'**Ongoing action (progressive tense).** *Estoy comiendo.* (I am eating.) Every Spanish progressive construction uses estar plus a gerund, never ser — this one has no exceptions.',
				],
			},
			{
				heading: 'The adjectives that flip meaning depending on which verb you use',
				body: [
					'A small set of adjectives change what they mean depending on which verb pairs with them, and these are the clearest proof that "permanent vs. temporary" isn\'t quite the right lens. *Ser aburrido* means "to be boring" (a trait); *estar aburrido* means "to be bored" (a state). *Ser listo* means "to be clever"; *estar listo* means "to be ready." *Ser malo* means "to be bad" (as a person); *estar malo* means "to be sick" or "to taste bad" (a condition). In each pair, ser names what something is and estar names what state it\'s currently in — the adjective\'s dictionary meaning barely changes, but the claim being made about the subject does.',
					'Ser also happens to be one of Spanish\'s most irregular verbs in its own right — its [full conjugation table](/ser-conjugation/) is worth a look if soy, era, and fui don\'t look to you like forms of the same word. And if por vs. para is next on your list of mixed-up pairs, [that one works on a similar logic](/por-vs-para/): stop translating "for" and ask what job the word is doing.',
				],
			},
		],
		faq: [
			{
				question: 'Is "ser is permanent, estar is temporary" actually correct?',
				answer: 'It\'s a useful starting shorthand but not a reliable rule. *Está muerto* ("he\'s dead") is estar describing something permanent, and *fue estudiante* ("he was a student") is ser describing something temporary. The more accurate distinction is whether the sentence defines the subject (ser) or reports its current state or condition (estar).',
			},
			{
				question: 'Why does "la fiesta es aquí" use ser when it\'s about location?',
				answer: 'Because the sentence is really saying where an event takes place, not where a physical object sits. Spanish treats the location of events (parties, meetings, concerts) as something ser defines, while the location of people and objects — *el libro está aquí* — uses estar. It looks like the same "location" category in English, but Spanish splits it in two.',
			},
			{
				question: 'What\'s the difference between "es aburrido" and "está aburrido"?',
				answer: '*Es aburrido* means the person or thing is boring — a characteristic. *Está aburrido* means the person is bored right now — a state. A handful of common adjectives (aburrido, listo, malo, rico, among others) shift meaning this way depending on which verb they\'re paired with.',
			},
			{
				question: 'Do all Spanish-speaking countries use ser and estar the same way?',
				answer: 'The core rule is consistent everywhere Spanish is spoken. What varies by region is mostly which side of a borderline adjective feels more natural in casual speech, not the underlying identity-vs-state logic, which holds across Spain and Latin America alike.',
			},
		],
		sources: [
			{ label: 'Real Academia Española — Nueva gramática básica: "Atributos con ser y estar"', url: 'https://www.rae.es/gram%C3%A1tica-b%C3%A1sica/el-atributo/el-atributo-en-las-oraciones-copulativas/atributos-con-ser-y-estar' },
			{ label: 'Real Academia Española — Diccionario panhispánico de dudas: "ser"', url: 'https://www.rae.es/dpd/ser' },
			{ label: 'Real Academia Española — Diccionario panhispánico de dudas: "estar"', url: 'https://www.rae.es/dpd/estar' },
		],
	},
	{
		slug: 'preterite-vs-imperfect',
		category: 'Grammar',
		title: 'Preterite vs. Imperfect: How Spanish Splits the Simple Past',
		description: 'English has one simple past tense; Spanish has two. The difference is whether the sentence treats the action as finished or as unfolding.',
		published: '2026-08-03',
		updated: '2026-08-03',
		coreSummary: 'The preterite (canté) presents a past action as a completed whole, with a clear edge. The imperfect (cantaba) presents a past action or state in progress, without marking where it started or ended. The choice isn\'t about how far back something happened or how long it lasted — a preterite action can span years and an imperfect one can span seconds — it\'s about which angle the speaker takes on it.',
		language: 'Spanish',
		sections: [
			{
				heading: 'English hides a distinction Spanish makes you choose',
				body: [
					'"I walked to school" is a single English sentence that could describe a one-time trip or a five-year daily routine — English doesn\'t force you to specify which. Spanish does: *caminé a la escuela* (preterite) says it happened, as a completed event; *caminaba a la escuela* (imperfect) says it was an ongoing or repeated action, described from the inside, with no stated beginning or end. Neither is more "past" than the other, and neither is inherently longer or shorter — the difference is entirely about how the speaker is framing the action, not when or how long it took.',
					'This is the single hardest thing about the pair for English speakers, because English simply doesn\'t require you to make this choice, so there\'s no equivalent instinct to draw on. Spanish grammar treats it as a question of aspect — whether an action is viewed as a finished whole or as unfolding — not a question of tense in the sense of "how long ago."',
				],
			},
			{
				heading: 'Preterite: a completed action with an edge',
				body: [
					'The preterite reports an action as done, viewed from outside as a single, bounded event, whether that event took an instant or a decade. *El mayordomo bajó las escaleras* ("The butler went down the stairs") reports that the descent was completed. *Vivió en México durante diez años* ("She lived in Mexico for ten years") is also preterite, even though ten years is a long stretch — because the sentence is framing that decade as a closed, completed chapter, not describing what daily life was like while it was happening.',
					'Preterite is the tense that moves a story\'s plot forward: it answers "then what happened?" A string of preterite verbs in a row reads as a sequence of completed events, one after another.',
				],
				image: {
					src: '/images/preterite-vs-imperfect-diagram.svg',
					alt: 'Diagram contrasting the preterite as a single completed point on a timeline ("bajó las escaleras," went down) with the imperfect as an ongoing wavy line with no marked start or end ("bajaba las escaleras," was going down).',
				},
			},
			{
				heading: 'Imperfect: an action viewed from the inside, without its edges',
				body: [
					'The imperfect presents a past situation from inside its own duration, without committing to when it started or ended. *El mayordomo bajaba las escaleras* ("The butler was going down the stairs") describes the descent in progress — it doesn\'t say whether he reached the bottom. Compare it to the preterite version above: same verb, same subject, but the imperfect leaves the ending open.',
					'Imperfect is the tense for background, description, and habitual or repeated actions in the past: *Cuando era niño, jugaba en el parque todos los días* ("When I was a kid, I used to play in the park every day") — a repeated routine with no single completed instance being reported. It\'s also the tense for setting a scene: *Llovía y hacía frío* ("It was raining and it was cold") describes the conditions surrounding an event, not the event itself.',
				],
			},
			{
				heading: 'Why the same sentence can use either, on purpose',
				body: [
					'The clearest way to see the distinction is a pair that uses the same verb and changes only the aspect. *Cuando llegué, ella dormía* ("When I arrived, she was sleeping") uses preterite for the arrival — a completed, single event — and imperfect for the sleeping, which was already in progress and had no marked start or end from the sentence\'s point of view. Swap the verbs: *Cuando llegaba, ella durmió* would be an odd sentence, because it treats the arrival as ongoing and the sleeping as a sudden, completed event, which doesn\'t match how these situations normally unfold.',
					'A narrative typically braids both together: imperfect sets the scene and describes ongoing conditions, preterite reports the events that interrupt or move through that scene. This is also why "how long ago" or "how long it lasted" is the wrong test — *vivió allí diez años* (preterite, a completed ten-year stretch) and *vivía allí cuando pasó el terremoto* (imperfect, an ongoing state interrupted by a preterite event) both involve "living somewhere" and can both refer to long periods; what differs is whether that period is being treated as a finished block or as an ongoing backdrop.',
					'One irregular verb worth knowing both forms of by heart is *ser* — its preterite (*fui, fue...*) and imperfect (*era, eras...*) are both common and completely different-looking from each other, which makes it a good verb to drill this distinction on. See the [full ser conjugation table](/ser-conjugation/) for every form.',
				],
			},
		],
		faq: [
			{
				question: 'Is the difference between preterite and imperfect about how long ago something happened?',
				answer: 'No — that\'s a common misconception. Both tenses can describe events from any point in the past. The real distinction is aspect: preterite presents an action as a completed whole, imperfect presents it as ongoing or habitual, without marking its start or end. A preterite action can span a decade; an imperfect one can span a single moment.',
			},
			{
				question: 'Why do "vivió" and "vivía" both mean "lived," and how do I know which to use?',
				answer: '*Vivió en México diez años* frames those ten years as a completed, closed chapter — as if answering "what did she do?" *Vivía en México cuando pasó el terremoto* frames the living-there as an ongoing backdrop that a specific event (the earthquake, in preterite) interrupted — closer to "what was going on when something else happened?"',
			},
			{
				question: 'Which tense do you use to describe the weather or a scene in the past?',
				answer: 'Imperfect, almost always: *llovía*, *hacía calor*, *el cielo estaba gris*. Background conditions are being described from the inside, with no stated beginning or end, which is exactly what the imperfect is for. A specific weather event that started and finished — *nevó por dos horas* ("it snowed for two hours") — can take the preterite instead.',
			},
			{
				question: 'Can the exact same habitual action be described in either tense?',
				answer: 'Yes, depending on whether the routine is bounded. *Jugaba en el parque todos los días* ("I used to play in the park every day") uses imperfect for an open-ended pattern with no stated start or end. *Jugué en el parque todos los días durante dos años* ("I played in the park every day for two years") uses preterite for the identical routine, but now framed as one completed, bounded chapter — the "for two years" is what closes it off and licenses the switch.',
			},
		],
		sources: [
			{ label: 'Real Academia Española — Nueva gramática de la lengua española: "El pretérito perfecto simple (canté)"', url: 'https://www.rae.es/gram%C3%A1tica/sintaxis/el-pret%C3%A9rito-perfecto-simple-cant%C3%A9' },
			{ label: 'Real Academia Española — Nueva gramática de la lengua española: "El pretérito imperfecto (cantaba)"', url: 'https://www.rae.es/gram%C3%A1tica/sintaxis/el-pret%C3%A9rito-imperfecto-cantaba-i-informaci%C3%B3n-de%C3%ADctica-e-informaci%C3%B3n-aspectual' },
		],
	},
	{
		slug: 'deja-vu-meaning',
		category: 'Loanwords',
		title: 'Déjà Vu Meaning: What It Actually Means (And Where the Phrase Comes From)',
		description: 'Déjà vu literally means "already seen" in French — but French dictionaries give the phrase a second, more everyday meaning that English never borrowed.',
		published: '2026-08-03',
		updated: '2026-08-03',
		coreSummary: 'In English, "déjà vu" names one specific thing: the eerie feeling of having already experienced a situation that is, in fact, new to you. In French, the phrase covers that same psychological sense but also does ordinary duty as a mild criticism — "nothing new, seen before, unoriginal" — a second meaning most English speakers who use the phrase have never encountered.',
		language: 'French',
		usageNote: {
			register: 'neutral',
			regionNote: 'English uses "déjà vu" only for the memory illusion. In everyday French, "c\'est du déjà-vu" is a common way to dismiss something as unoriginal or predictable — closer to English "seen it all before" or "nothing new here" — a sense that never made the jump into English.',
		},
		sections: [
			{
				heading: 'Literally "already seen" — and French gives it two jobs',
				body: [
					'*Déjà* means "already" and *vu* is the past participle of *voir*, "to see" — so *déjà vu* is, word for word, "already seen." That much lines up with how English speakers use the phrase. What doesn\'t line up is that French dictionaries record two separate senses for it. The Larousse dictionary lists the phrase as covering both "a memory disorder giving the sudden and intense impression of having already lived through the present situation in the past," and, separately, "something that is not new, that is banal, without originality."',
					'That second sense is alive in everyday French in a way it never became in English: *c\'est du déjà-vu* is an ordinary way to say a film, a plot twist, or a political promise is predictable and unoriginal — no memory illusion involved, just a shrug at something recycled.',
				],
			},
			{
				heading: 'How English narrowed it to one specific feeling',
				body: [
					'Merriam-Webster defines déjà vu, in its main English sense, as "the illusion of remembering scenes and events when experienced for the first time" — a feeling that you have seen or heard something before, even though you haven\'t. That\'s the sense English adopted wholesale and the sense that stuck, to the exclusion of the French "unoriginal" meaning.',
					'The term itself is relatively young as coined vocabulary: the French philosopher Émile Boirac first used it in 1876, in an open letter to the journal *Revue Philosophique* describing "le sentiment du déjà vu" as a specific type of memory illusion. He returned to the term later in his own writing on psychical research, but the coining moment is the 1876 letter, not a book. Either way, the psychological sense is a fairly recent, deliberately coined piece of vocabulary — not an old expression that gradually picked up its clinical meaning over centuries.',
				],
			},
			{
				heading: 'What\'s actually happening when you get it',
				body: [
					'Déjà vu is a studied, mainstream topic in memory research, not a fringe idea. One line of explanation treats it as a momentary miscommunication between the brain\'s temporal lobe, where memories are stored, and the hippocampus, which handles short-term memory — essentially a signal-timing glitch that makes a brand-new scene register briefly as familiar. Other explanations point to inattentiveness during a similar past experience, a partially forgotten memory being triggered by a few matching details, or a minor processing error rather than any dramatic mix-up.',
					'What research does not support is the idea that déjà vu means something is wrong with you: on its own, an occasional déjà vu experience is common and unremarkable. Frequent or prolonged episodes are sometimes discussed alongside certain neurological conditions in clinical literature, which is a separate topic from the ordinary, occasional version almost everyone experiences — worth raising with a doctor if it becomes frequent, not something to self-diagnose from a word-meaning page.',
				],
			},
			{
				heading: 'The word for the opposite feeling',
				body: [
					'If déjà vu is something new feeling falsely familiar, *jamais vu* — literally "never seen" — is the reverse: something genuinely familiar suddenly feeling strange or unrecognized. Cleveland Clinic describes it as the feeling that something you know well seems unreal or unfamiliar, and gives the common example of staring at an ordinary word until it stops looking like a real word. It\'s the less famous sibling of déjà vu, but it\'s a real, separately studied phenomenon, not just wordplay on the more famous term.',
					'Déjà vu belongs to a small club of loanwords English kept in their original form because no native word covered the same specific ground — [schadenfreude](/schadenfreude-meaning/) is the German entry in that same club.',
				],
			},
		],
		faq: [
			{
				question: 'Who coined the term "déjà vu"?',
				answer: 'The French philosopher Émile Boirac first used it in 1876, in an open letter to the journal Revue Philosophique describing "le sentiment du déjà vu" as a type of memory illusion — not, as sometimes reported, in one of his later books.',
			},
			{
				question: 'Does "déjà-vu" mean something different in French than it does in English?',
				answer: 'English uses it only for the memory-illusion sense. French dictionaries like Larousse also record a second, everyday sense: something unoriginal or predictable, as in "c\'est du déjà-vu" ("seen it all before"). English never adopted that second meaning.',
			},
			{
				question: 'Is déjà vu a sign that something is wrong with your brain?',
				answer: 'An occasional déjà vu experience is common and not a cause for concern on its own. It\'s a well-studied, mainstream topic in memory research. Frequent or prolonged episodes are a different matter and worth discussing with a doctor, but that\'s a distinct question from the everyday version most people experience now and then.',
			},
			{
				question: 'What\'s the opposite of déjà vu called?',
				answer: '"Jamais vu" — literally "never seen." It\'s the feeling that something genuinely familiar suddenly seems strange or unrecognizable, such as staring at a common word until it stops looking like a real word.',
			},
		],
		sources: [
			{ label: 'Larousse — Définitions: "déjà-vu"', url: 'https://www.larousse.fr/dictionnaires/francais/d%C3%A9j%C3%A0-vu/22991' },
			{ label: 'Merriam-Webster — "deja vu"', url: 'https://www.merriam-webster.com/dictionary/deja%20vu' },
			{ label: 'Cleveland Clinic — "What Is Jamais Vu?"', url: 'https://health.clevelandclinic.org/jamais-vu' },
			{ label: 'Wikipedia — "Émile Boirac"', url: 'https://en.wikipedia.org/wiki/%C3%89mile_Boirac' },
			{ label: 'NCBI/PMC — "Hippocampal involvement in nonpathological déjà vu"', url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6043696/' },
		],
	},
	{
		slug: 'schadenfreude-meaning',
		category: 'Loanwords',
		title: 'Schadenfreude Meaning: The German Word English Never Had',
		description: 'Schadenfreude names the pleasure of watching someone else\'s misfortune. German built the word from two plain nouns; English just borrowed it.',
		published: '2026-08-03',
		updated: '2026-08-03',
		coreSummary: 'Schadenfreude is a German compound noun — Schaden ("harm, damage") plus Freude ("joy") — meaning pleasure taken in someone else\'s misfortune. Duden, the standard German dictionary, defines it as "boshafte Freude über das Missgeschick, Unglück eines andern" ("malicious joy at another\'s mishap or misfortune"), while the corpus-based dictionary DWDS gives a more neutral phrasing without the "malicious" qualifier. English adopted the German word directly rather than translate it, largely because no single English word names that exact feeling.',
		language: 'German',
		usageNote: {
			register: 'neutral',
			regionNote: 'Not a slang or vulgar term in either language — it\'s an ordinary, everyday noun in German, and a fairly literary or formal-register borrowing in English, more likely to show up in writing or a pointed remark than in casual small talk.',
		},
		sections: [
			{
				heading: 'A compound word English never got around to building',
				body: [
					'German builds new words by fusing existing ones together, and *Schadenfreude* is one of the clearest examples: *Schaden* means "harm" or "damage," *Freude* means "joy," and stacking them gives you, transparently, "harm-joy." Duden, the standard reference dictionary for German, defines it as "boshafte Freude über das Missgeschick, Unglück eines andern" — malicious joy at another person\'s mishap or misfortune.',
					'English could have built the same compound out of its own materials — "harm-joy" isn\'t an unreasonable calque — but it never did. Instead, English speakers reached for the ready-made German word once they needed to name the feeling precisely, which is the common path a loanword takes when the borrowing language has the concept but never bothered to name it on its own.',
				],
			},
			{
				heading: 'The specific feeling it names',
				body: [
					'The precision matters: Schadenfreude isn\'t pleasure at just anything bad happening, and it isn\'t wanting harm on someone in advance. It\'s the specific, narrower reaction of enjoying misfortune that has already happened to someone else — a rival sports team blowing a lead, a driver who cut you off getting pulled over two blocks later, a smug prediction aging badly. The emotion is common enough to be near-universal, which is exactly why a one-word label for it was useful enough to travel between languages.',
					'German dictionaries themselves don\'t fully agree on how much moral judgment to build into the definition. Duden\'s "boshafte Freude" leans into "malicious," while DWDS defines the same word without that qualifier, as simply pleasure at another\'s mishap. Psychologists studying the emotion generally treat it the second way: a description of a common reaction, not a verdict on the character of whoever feels it.',
				],
			},
			{
				heading: 'How to actually use it in an English sentence',
				body: [
					'In English, Schadenfreude functions as an uncountable noun, almost always used on its own rather than pluralized or modified heavily: *"There was more than a little schadenfreude in the office when the loudest critic\'s project got cancelled."* It keeps its German capitalization in careful writing (German capitalizes all nouns), though English style guides vary and lowercase *schadenfreude* is common and accepted.',
					'Pronunciation is the other thing that trips up new users: it\'s roughly *SHAH-dən-froy-də*, with the "sch" as an English "sh" sound and the final "e" pronounced as a short, weak vowel rather than silent.',
					'It sits in the same category as words like [déjà vu](/deja-vu-meaning/) and [senpai](/senpai-meaning/) — a foreign phrase English adopted wholesale rather than translate, because nothing native said quite the same thing.',
				],
			},
			{
				heading: '"Schadenfreude" isn\'t quite the same thing as "gloating"',
				body: [
					'English does have words that sit near schadenfreude, and it\'s worth being precise about how they differ. "Gloating" describes openly, visibly expressing triumph over someone else\'s failure, often when you had some hand in causing it or in besting them directly — it\'s an action, not just a feeling, and it usually shows. Schadenfreude is the private feeling itself, whether or not you ever act on it or had anything to do with causing the misfortune in the first place: you can feel schadenfreude silently, watching the news, about a stranger\'s bad luck you had zero part in.',
					'That\'s the gap German filled and English didn\'t: English has words for showing triumph (gloating, crowing) but no single native word for the quieter, purely internal version of the same reaction, which is exactly the gap Schadenfreude was borrowed to fill.',
				],
			},
		],
		faq: [
			{
				question: 'What does "schadenfreude" literally mean, word for word?',
				answer: 'It\'s a compound of two German nouns: Schaden ("harm" or "damage") and Freude ("joy"). Duden defines the whole word as "boshafte Freude über das Missgeschick, Unglück eines andern" — malicious joy at another\'s mishap or misfortune — though the dictionary DWDS phrases the same meaning without the "malicious" qualifier.',
			},
			{
				question: 'Is schadenfreude the same thing as being cruel or mean-spirited?',
				answer: 'Not exactly. It describes a specific, common emotional reaction — enjoying someone else\'s bad luck, often in a minor or karmic-feeling situation — rather than actively wishing harm on someone. The word names the feeling; it doesn\'t pass judgment on whether feeling it makes someone a bad person.',
			},
			{
				question: 'How do you pronounce schadenfreude?',
				answer: 'Roughly SHAH-dən-froy-də: the "sch" is pronounced like English "sh," and the final "e" is a short, weak vowel sound rather than silent, as German does not silence word-final "e" the way English typically does.',
			},
			{
				question: 'Is schadenfreude a rude or vulgar word in German?',
				answer: 'No — it\'s a completely ordinary, everyday noun in German, with no vulgar or offensive connotation. In English, it tends to sound a bit more formal or literary simply because it\'s a borrowed word rather than because of anything impolite about it.',
			},
		],
		sources: [
			{ label: 'Duden — "Schadenfreude"', url: 'https://www.duden.de/rechtschreibung/Schadenfreude' },
			{ label: 'DWDS — "Schadenfreude"', url: 'https://www.dwds.de/wb/Schadenfreude' },
		],
	},
	{
		slug: 'senpai-meaning',
		category: 'Loanwords',
		title: 'Senpai Meaning: What It Actually Means in Japanese (Not Just Anime)',
		description: 'Before it was an internet meme, senpai named a real, structured relationship in Japanese schools and workplaces — not just "someone senior."',
		published: '2026-08-03',
		updated: '2026-08-03',
		coreSummary: 'Senpai (先輩) literally combines 先 ("ahead, before") with 輩 ("fellow, companion, generation") to mean a senior member of the same school, company, or group — someone who joined or started before you and, by the norms of the relationship, is expected to mentor the people who came after. The junior counterpart is kōhai (後輩). English absorbed only the internet-meme sense of the word; the Oxford English Dictionary added "senpai" to its December 2025 update alongside a batch of other Japanese and Korean loanwords.',
		language: 'Japanese',
		usageNote: {
			register: 'neutral',
			regionNote: 'In Japanese, senpai is a neutral, everyday term used seriously in schools, companies, and clubs. The casual, jokey English usage ("notice me, senpai," used for anyone whose attention you want) is an internet-meme sense that grew out of anime fandom starting around 2012 and has little to do with how the word functions in Japanese.',
		},
		sections: [
			{
				heading: 'What the kanji actually says',
				body: [
					'先輩 is written with two characters. 先 (*sen*) means "before, ahead, previous" — it\'s the same character used in words like *saki* (先, "ahead" or "the future," depending on context). 輩 (*hai*, here read *pai*) means "fellow, companion, people of the same group" — it shows up in words for peer groups and generations. Put together, senpai means something close to "one of us who came before" rather than simply "someone older" or "someone in charge." The Japanese-English dictionary Jisho glosses it as "senior (at school, work, etc.); superior; elder; older person; predecessor."',
					'The junior counterpart, kōhai (後輩), swaps 先 for 後 (*go/kō*, "after, behind"), giving the mirror-image "one of us who came after."',
				],
			},
			{
				heading: 'A real relationship, not just a rank',
				body: [
					'Senpai-kōhai is a structured, reciprocal relationship built into Japanese schools, sports clubs, and workplaces, not just a label for "older person." Someone becomes your senpai by having joined the same school, club, team, or company before you did — age isn\'t the deciding factor, tenure is. A 22-year-old who joined a company a year before a 30-year-old new hire is still that new hire\'s senpai.',
					'The relationship carries real obligations in both directions: a senpai is expected to look out for and mentor their kōhai, showing them the ropes and taking some responsibility for how they\'re doing, while a kōhai is expected to show a degree of deference and respect in return. It\'s closer to a built-in mentorship system than a simple hierarchy, and it\'s one reason the concept doesn\'t map cleanly onto a single English word — "senior" captures the rank but misses the mentoring expectation.',
					'One rule that surprises learners: you don\'t call yourself senpai. It\'s a status granted by others, not a label you claim for yourself — a Japanese speaker introducing themselves would never say "I\'m your senpai," even if the relationship is objectively true.',
					'Senpai also functions as an honorific suffix, the same way *-san*, *-kun*, and *-chan* do: attached directly to a name, as in *Tanaka-senpai*, it\'s a standard, polite way to address someone senior, whether by surname or first name, and it\'s gender-neutral. The relationship is generally described as being at its strictest inside school club activities (*bukatsu*) — sports clubs like baseball, kendo, or soccer, where the senpai-kōhai structure governs everything from how practice is run to how new members are expected to speak to senior ones.',
				],
			},
			{
				heading: 'How English narrowed it into a meme, then a dictionary entry',
				body: [
					'The English-internet sense of senpai — used loosely for anyone whose attention or approval you want, romantic or otherwise — grew out of anime and manga fandom, with the phrase "notice me, senpai" spreading on sites like Tumblr starting around 2012 and picking up further momentum once it was used repeatedly by high-profile YouTubers. That usage strips out almost everything about the structured senpai-kōhai relationship and keeps only "someone whose attention is desirable," which is a genuinely different meaning from the Japanese original.',
					'The word has since moved from internet slang toward formal recognition: the Oxford English Dictionary added "senpai" in its December 2025 update, alongside other recently adopted Japanese and Korean words. That\'s a fairly rare trajectory for a meme-driven usage — most internet slang never reaches a major dictionary at all, unlike older borrowings such as [schadenfreude](/schadenfreude-meaning/), which entered English decades ago through ordinary usage rather than a meme.',
				],
			},
		],
		faq: [
			{
				question: 'Is a senpai always older than their kōhai?',
				answer: 'Not necessarily. The relationship is based on who joined a school, club, or company first, not on age. A younger person who started earlier is still senior to an older person who started later.',
			},
			{
				question: 'Can you call yourself "senpai"?',
				answer: 'No — in Japanese, senpai is a status granted by others based on the relationship, not a label you apply to yourself. Introducing yourself as someone\'s senpai would sound odd in Japanese, even where the relationship genuinely applies.',
			},
			{
				question: 'What\'s the difference between the Japanese meaning of senpai and the internet meme?',
				answer: 'In Japanese, senpai describes a specific, reciprocal mentorship relationship at school, work, or in a club. The English internet usage — as in "notice me, senpai" — strips that down to just "someone whose attention you want," a much narrower and more casual sense that spread through anime fandom starting around 2012.',
			},
			{
				question: 'Is "senpai" an official English word now?',
				answer: 'It\'s recognized by at least one major dictionary: the Oxford English Dictionary added "senpai" in its December 2025 update, alongside a batch of other Japanese and Korean loanwords.',
			},
		],
		sources: [
			{ label: 'Jisho.org — Japanese-English dictionary entry for 先輩', url: 'https://jisho.org/word/%E5%85%88%E8%BC%A9' },
			{ label: 'South China Morning Post — "Senpai, bingsu, ramyeon: new Korean and Japanese words in the Oxford English Dictionary"', url: 'https://www.scmp.com/lifestyle/entertainment/article/3340137/senpai-bingsu-ramyeon-new-korean-and-japanese-words-oxford-english-dictionary' },
			{ label: 'Coto Academy — "What is Senpai (先輩) in Japanese?"', url: 'https://cotoacademy.com/learn-japanese-blog-senpai-meaning/' },
		],
	},
	{
		slug: 'happy-birthday-in-spanish',
		category: 'Phrases',
		title: 'How to Say Happy Birthday in Spanish (Plus the Song Most People Actually Sing)',
		description: '"Feliz cumpleaños" is the same across the Spanish-speaking world — but in Mexico, the song sung at the party usually isn\'t the English tune translated.',
		published: '2026-08-03',
		updated: '2026-08-03',
		coreSummary: '"Happy birthday" in Spanish is Feliz cumpleaños, used identically across every Spanish-speaking country with no regional variant in the phrase itself. Cumpleaños literally means "years completed" (from cumplir, "to complete/fulfill," plus años, "years"). In Mexico and increasingly beyond it, the song actually sung at birthdays is often not a translation of the English tune at all, but Las Mañanitas, a traditional song with its own separate origins.',
		language: 'Spanish',
		sections: [
			{
				heading: 'The phrase itself, and what it literally means',
				body: [
					'*Feliz cumpleaños* — *feliz* ("happy") plus *cumpleaños* ("birthday") — is the standard phrase everywhere Spanish is spoken, with no meaningful regional split the way some other phrases on this site have. *Cumpleaños* is itself a compressed piece of grammar: it comes from *cumple* (a form of *cumplir*, "to complete" or "to fulfill") plus *años* ("years"), so the word literally means "[one] completes years." The Real Academia Española defines it simply as "aniversario del nacimiento de una persona" — the anniversary of a person\'s birth — and notes that as a noun it\'s written as one word (*su cumpleaños*), while the underlying verb phrase stays two words (*mamá cumple años hoy*, "mom has a birthday today," literally "turns years today").',
					'A shortened, casual version is common in speech and texting: *¡Feliz cumple!* drops the second half of *cumpleaños* the way English speakers might say "happy birthday" instead of spelling out a longer phrase.',
					'The greeting is also commonly followed by a second line rather than left standing alone: *¡Feliz cumpleaños! Que cumplas muchos más* — literally "may you complete many more," closer in spirit to the English "many happy returns" than to a literal translation. It\'s a warm, standard add-on across the Spanish-speaking world, not a regional variant of the greeting itself.',
				],
			},
			{
				heading: 'Las Mañanitas: the song most Mexican households actually sing',
				body: [
					'English speakers often assume the Spanish birthday song is just a translation of "Happy Birthday to You" — and a direct Spanish adaptation of that tune does circulate informally in several countries, usually opening with the line *cumpleaños feliz*. But in Mexico, and in many households with Mexican roots elsewhere, the song that actually gets sung is a different piece entirely: *Las Mañanitas* ("The Little Mornings"), traditionally performed at the crack of dawn, with family gathering outside the birthday person\'s door, or a hired mariachi band, to wake them up with it.',
					'Las Mañanitas didn\'t start life as a birthday song. It began as a *ranchera* — a traditional Mexican folk-song style — and only gradually became specifically associated with birthdays, alongside weddings, baptisms, and other family celebrations, before settling into its current role as Mexico\'s default birthday song. Its lyrics compare the beauty of the dawn to the person being celebrated, rather than simply wishing them a happy day the way the English song does.',
					'Once the celebration is over, the two other everyday phrases worth having on hand are [good night in Spanish](/good-night-in-spanish/) and the different registers behind [saying "I love you" in Spanish](/i-love-you-in-spanish/) — both come with the same kind of nuance that a direct translation misses.',
				],
			},
		],
		faq: [
			{
				question: 'Does "feliz cumpleaños" change between Spain and Latin America?',
				answer: 'No — the phrase itself is identical across every Spanish-speaking country. What varies is the surrounding birthday tradition (like Mexico\'s Las Mañanitas), not the greeting.',
			},
			{
				question: 'What does "cumpleaños" literally mean?',
				answer: '"Years completed" or "fulfills years" — it comes from cumplir ("to complete, to fulfill") plus años ("years"). The Real Academia Española defines the noun form as the anniversary of a person\'s birth.',
			},
			{
				question: 'Is there a casual, shortened way to say it?',
				answer: 'Yes — "¡Feliz cumple!" drops the second half of cumpleaños, similar to how English speakers might shorten a greeting in casual speech or texting.',
			},
			{
				question: 'Is Las Mañanitas the same song as the Spanish "Happy Birthday to You"?',
				answer: 'No, they\'re different songs. A direct Spanish-language adaptation of the English "Happy Birthday to You" tune does exist and gets sung informally in various countries. Las Mañanitas is a separate, older traditional Mexican song that began as a ranchera and became linked to birthdays over time — it\'s the one most closely associated with Mexican birthday celebrations specifically.',
			},
		],
		sources: [
			{ label: 'Real Academia Española — Diccionario de la lengua española: "cumpleaños"', url: 'https://dle.rae.es/cumplea%C3%B1os' },
			{ label: 'Mexperience — "Las Mañanitas: Mexico\'s Gift to Birthdays"', url: 'https://www.mexperience.com/mexicos-gift-to-birthdays/' },
		],
	},
	{
		slug: 'good-night-in-spanish',
		category: 'Phrases',
		title: 'How to Say Good Night in Spanish (And Why It\'s Not Just a Farewell)',
		description: '"Buenas noches" translates as "good night" — but in Spanish it\'s mainly a greeting said on arrival after dark, not a farewell before bed.',
		published: '2026-08-03',
		updated: '2026-08-03',
		coreSummary: '"Good night" in Spanish is buenas noches, but its main job is different from the English phrase: Spanish speakers use it chiefly as a greeting when arriving somewhere after dark, the way English speakers say "good evening" — not primarily as a farewell before bed. It can also be used to say goodbye at night, but treating it as only a farewell (the default English instinct) misses how it\'s used most of the time.',
		language: 'Spanish',
		sections: [
			{
				heading: 'One phrase Spanish uses for both hello and goodbye',
				body: [
					'*Buenas noches* sits alongside *buenos días* ("good morning") and *buenas tardes* ("good afternoon/evening") as one of the three time-of-day greetings that structure everyday Spanish small talk. Like the other two, its primary use is as a greeting, not a farewell: if you walk into a restaurant, a shop, or a friend\'s home after dark, *buenas noches* is what you say on arrival, the direct equivalent of English "good evening" in that moment — not "good night."',
					'That\'s the detail that catches English speakers off guard, because in English "good night" is used almost exclusively as something you say when leaving or heading to bed, never as a greeting on arrival. Spanish overlaps the greeting and farewell functions into the same phrase, and context — are you walking in or walking out? — does the disambiguating work that English splits across two different phrases ("good evening" to arrive, "good night" to leave).',
				],
			},
			{
				heading: 'When it does work as a farewell',
				body: [
					'*Buenas noches* is also perfectly normal as a farewell at night, especially right before people go to sleep or head home for the evening — that use does exist and isn\'t wrong. The point isn\'t that the farewell sense is incorrect, it\'s that defaulting to treating it as *only* a farewell, the way the English phrase works, will make you say goodbye when you meant to say hello, or miss that someone greeting you late in the evening isn\'t actually leaving.',
					'A shortened, casual version, *¡Buenas!*, can stand in for whichever of the three time-of-day greetings fits the moment, similar to how an English speaker might just say "evening" instead of the full "good evening." It isn\'t universal, though: the Real Academia Española notes it\'s a colloquial form used in Spain, the Río de la Plata area, and parts of the Andean and Central American regions, rather than something you\'ll hear everywhere Spanish is spoken.',
				],
			},
			{
				heading: 'The phrases for the moment you actually head to bed',
				body: [
					'For the specific moment of tucking in — not just marking that it\'s evening — Spanish reaches for different phrases built on *dormir* ("to sleep") or *descansar* ("to rest"). *Que duermas bien* ("sleep well" / "sleep tight") talks about the sleep itself; *que descanses* talks more broadly about resting, closer to "have a restful night" than to sleep specifically. Both are genuine, commonly used wishes, and the choice between them is mostly about which aspect — the sleeping or the resting — a speaker wants to emphasize, not a hard rule.',
					'Register works the same way for both verbs, independent of which one you pick: *que duermas bien* is the informal *tú* form, and its direct formal counterpart, same verb, is *que duerma bien* (*usted*). *Descansar* follows the identical pattern — *que descanses* (tú) versus *que descanse* (usted) — so the dormir-versus-descansar choice and the tú-versus-usted choice are two separate decisions, not one. A parent putting a child to bed is more likely to reach for a simple *¡a dormir!* ("off to bed!") than any of these — a command, not a wish.',
				],
			},
		],
		faq: [
			{
				question: 'Can you use "buenas noches" to say hello?',
				answer: 'Yes — after dark, it\'s commonly used as a greeting when arriving somewhere, the way English speakers use "good evening." This is actually its primary use, not a secondary one.',
			},
			{
				question: 'How do you know if someone means hello or goodbye when they say "buenas noches"?',
				answer: 'Context does the work: if someone says it as you\'re arriving, they\'re greeting you; if they say it as you or they are leaving, it\'s a farewell. The phrase itself doesn\'t distinguish the two the way English splits "good evening" (hello) from "good night" (goodbye).',
			},
			{
				question: 'Is there a shortened, casual version?',
				answer: 'Yes — "¡Buenas!" is a casual shortening that can cover any of the three time-of-day greetings (buenos días, buenas tardes, buenas noches), similar to an English speaker just saying "morning" or "evening." The Real Academia Española notes it\'s specifically a colloquial form of Spain, the Río de la Plata area, and parts of the Andean and Central American regions, not something used everywhere. For other everyday phrases with the same kind of hidden nuance, see how to say [happy birthday](/happy-birthday-in-spanish/) and ["I love you"](/i-love-you-in-spanish/) in Spanish.',
			},
			{
				question: 'When does "buenas noches" become the right greeting instead of "buenas tardes"?',
				answer: 'Roughly the same threshold as English "good evening" versus "good afternoon" — once it\'s dark or evening has clearly set in. There\'s no fixed clock time; it follows the same fuzzy, context-based sense of "evening" that English speakers already use for the tardes-to-noches switch.',
			},
		],
		sources: [
			{ label: 'Real Academia Española — Español al día: "¿Cuál es la fórmula de saludo más adecuada...?"', url: 'https://www.rae.es/espanol-al-dia/cual-es-la-formula-de-saludo-mas-adecuada-buen-dia-o-buenos-dias-y-durante-la-tarde' },
		],
	},
	{
		slug: 'i-love-you-in-spanish',
		category: 'Phrases',
		title: 'How to Say I Love You in Spanish: Te Quiero vs. Te Amo',
		description: 'Spanish gives you two ways to say "I love you," and picking the wrong one either undersells how you feel or comes on far stronger than you meant to.',
		published: '2026-08-03',
		updated: '2026-08-03',
		coreSummary: 'Te quiero and te amo both translate as "I love you," but they aren\'t interchangeable. Te quiero is the everyday version, used for friends, family, and romantic partners alike, and doesn\'t necessarily signal deep romantic seriousness. Te amo is more intense, most often used for committed romantic love, though it also shows up between very close family members (especially parents and children) in parts of Latin America. Spain leans toward using te quiero even between romantic partners, while Latin America uses both, generally keeping te amo for the most serious declarations.',
		language: 'Spanish',
		usageNote: {
			regionNote: 'Spain tends to favor te quiero broadly, even between long-term partners, while Latin American Spanish uses both — with te amo more consistently reserved for serious romantic commitment. This is a tendency, not a hard boundary; you\'ll hear exceptions in both regions.',
		},
		sections: [
			{
				heading: 'Two verbs, two intensities',
				body: [
					'Spanish has two common verbs that can both be translated "to love": *querer* (whose core meaning is closer to "to want" or "to care for") and *amar* (a more elevated, specifically love-focused verb). *Te quiero* and *te amo* — "I love/want you" and "I love you," respectively — pull from those two verbs, and native speakers treat them as genuinely different statements, not stylistic variants of the same one.',
				],
			},
			{
				heading: 'Te quiero: the everyday version',
				body: [
					'*Te quiero* is the more common of the two by a wide margin, and it\'s used across a much wider range of relationships: friends tell each other *te quiero*, family members say it routinely, and romantic partners use it too, especially outside of the most serious or formal declarations. Because *querer* also means "to want," the phrase carries a lighter, warmer connotation of care and affection rather than an all-consuming romantic claim — closer to "I care about you deeply" than to a wedding-vow-level statement.',
					'If you\'re unsure which to use with a new romantic partner, *te quiero* is the safer default precisely because it doesn\'t overcommit.',
				],
			},
			{
				heading: 'Te amo: saved for something bigger',
				body: [
					'*Te amo* is reserved, by convention, for deeper, more serious romantic love — the kind of statement that typically comes after a relationship has had real time to develop, not something said casually or early on. Using it too soon in a new romance can read as unexpectedly intense or even a little theatrical to a native speaker, roughly the way declaring "I am deeply, permanently in love with you" would land oddly if said to someone you\'d been dating for two weeks.',
					'Romantic intensity isn\'t the only place *te amo* shows up, though: in Mexico and especially in Argentina, it\'s also commonly used between parents and children, as a sign of serious, weighty affection rather than romance. So "almost always romantic" is the right instinct for a new acquaintance, but not an absolute rule — the common thread across every use of *te amo* is depth of feeling, not necessarily romance specifically.',
				],
			},
			{
				heading: 'A regional wrinkle worth knowing',
				body: [
					'The intensity gap between the two phrases holds everywhere Spanish is spoken, but which one gets used day-to-day varies by region. In Spain, *te quiero* is the phrase couples typically use even in long-term, committed relationships — *te amo* can sound almost too formal or literary for everyday use. In much of Latin America, both phrases are in active use, with *te amo* more reliably reserved for genuinely serious romantic love and *te quiero* covering everything from friendship to an early relationship.',
					'For a warm, clearly non-romantic alternative — telling a friend you value them without touching either "love" verb — Spanish speakers often reach for *me caes muy bien* ("I like you a lot," literally closer to "you strike me very well") instead.',
				],
			},
			{
				heading: 'A third rung below both: "me gustas"',
				body: [
					'There\'s a lighter step below even *te quiero* for early romantic interest: *me gustas* ("I like you," in the sense of "I\'m into you," not the plain-liking sense of *me gusta* for a food or a movie). It signals attraction without committing to anything like love — closer to a crush confession than a relationship milestone, and often what gets said before either *te quiero* or *te amo* is on the table at all.',
					'Put in order of escalating commitment, the three sit roughly as *me gustas* (attraction, no commitment implied) → *te quiero* (affection, appropriate for friends, family, and established but not necessarily deeply serious romance) → *te amo* (deep, committed romantic love). None of the three is interchangeable with either of the others.',
				],
			},
		],
		faq: [
			{
				question: 'Can you say "te quiero" to a friend without it sounding romantic?',
				answer: 'Yes — te quiero is routinely used between friends and family members with no romantic implication. Context (who you\'re talking to, the relationship) makes the meaning clear, the same way "I love you" can be platonic or romantic in English depending on who says it to whom.',
			},
			{
				question: 'Is "te amo" too intense for a new relationship?',
				answer: 'By convention, generally yes. Te amo is typically reserved for serious, established romantic love, and using it very early in a relationship can come across as more intense than intended.',
			},
			{
				question: 'Do Spain and Latin America use these phrases differently?',
				answer: 'The underlying intensity difference is consistent everywhere, but usage habits vary: Spain tends to favor te quiero even for long-term partners, while Latin American Spanish uses both, generally keeping te amo for more serious declarations. Treat this as a regional tendency rather than a strict rule.',
			},
			{
				question: 'Is there a way to express fondness for a friend without using "love" at all?',
				answer: 'Yes — "me caes muy bien" ("I like you a lot") is a common, warm way to express platonic appreciation without touching querer or amar, useful when "I love you" would feel like too much even in its lighter, platonic English sense. For more everyday Spanish phrases with this kind of nuance, see [happy birthday](/happy-birthday-in-spanish/) and [good night](/good-night-in-spanish/) in Spanish.',
			},
		],
		sources: [
			{ label: 'Real Academia Española — Diccionario de la lengua española: "querer"', url: 'https://dle.rae.es/querer' },
			{ label: 'Real Academia Española — Diccionario de la lengua española: "amar"', url: 'https://dle.rae.es/amar' },
			{ label: 'Na\'atik Language & Culture Institute — "¿Te quiero o te amo? ¿Me gustas o me caes bien?"', url: 'https://naatikmexico.org/blog/te-quiero-o-te-amo-me-gustas-o-me-caes-bien' },
		],
	},
	{
		slug: 'ser-conjugation',
		category: 'Conjugations',
		title: 'Ser Conjugation: The Complete Guide to Every Tense',
		description: 'Ser is Spanish\'s most irregular verb, stitched from two Latin verbs by history. Every tense here is code-generated and hand-verified, not typed from memory.',
		published: '2026-08-03',
		updated: '2026-08-03',
		coreSummary: 'Ser means "to be" in the identity/characteristics sense (see Ser vs. Estar), and it is one of only a handful of fully irregular Spanish verbs — soy, eres, es bear no resemblance to a regular -er verb\'s endings because they descend from an entirely different Latin verb than the rest of ser\'s own paradigm. The full conjugation table below covers present, preterite, imperfect, future, conditional, present subjunctive, and the affirmative imperative.',
		language: 'Spanish',
		sections: [
			{
				heading: 'Why ser breaks every conjugation pattern',
				body: [
					'Regular Spanish verbs conjugate by attaching a predictable set of endings to a stem — that\'s the whole system behind verbs like hablar or vivir. Ser doesn\'t follow that system because, historically, it isn\'t really one verb: Spanish ser is suppletive, meaning its paradigm was assembled from two different Latin verbs rather than descending cleanly from one. According to the linguistic research site Spanish Linguist, the present-tense indicative forms (*soy, eres, es, somos, sois, son*) descend from the Latin verb *esse* ("to be"), while nearly everything else in ser\'s conjugation — the infinitive itself, the subjunctive, the future and conditional stems, the *tú* imperative (*sé*) — descends instead from Latin *sedere*, "to sit."',
					'That\'s the actual reason *soy* and *sería* don\'t look like they belong to the same verb at first glance: for most of Spanish\'s history, they effectively didn\'t. Two separate Latin verbs merged into a single paradigm, and Spanish speakers today just learn the result as one (extremely irregular) verb.',
				],
			},
			{
				heading: 'How to actually use each tense',
				body: [
					'**Present** (*soy, eres, es...*) states identity, origin, and inherent characteristics right now: *Soy de Chile.* (I\'m from Chile.)',
					'**Preterite** (*fui, fuiste, fue...*) — notably identical in form to the preterite of *ir* ("to go") — reports a completed state in the past: *Fue un buen año.* (It was a good year.) Context is the only thing that tells *fue* apart from "he/she/it went."',
					'**Imperfect** (*era, eras, era...*) describes an ongoing past state with no marked beginning or end: *Era muy joven.* (I was very young.) If the [preterite-versus-imperfect distinction](/preterite-vs-imperfect/) itself is still fuzzy, ser\'s two very different-looking past forms are a good pair to drill it on.',
					'**Future** (*seré, serás, será...*) and **conditional** (*sería, serías, sería...*) work the way they do for any verb: future for what will be, conditional for what would be.',
					'**Present subjunctive** (*sea, seas, sea...*) shows up after expressions of doubt, wish, or emotion: *Espero que sea verdad.* (I hope it\'s true.)',
					'**Affirmative imperative** has no *yo* form (commands aren\'t given to yourself) and uses a five-slot pattern instead of six: *¡Sé fuerte!* (Be strong!) uses the irregular *tú* command form *sé*, which — confusingly for learners — is spelled identically to *sé* meaning "I know" (from *saber*), though the accent-free spelling is correct for both and context always makes the meaning clear.',
				],
			},
			{
				heading: 'A regional variant the table above doesn\'t cover: voseo',
				body: [
					'The table on this page uses *tú* for the informal singular "you," which is standard across Spain and most of Latin America. But in Argentina, Uruguay, and parts of Central America, everyday speech uses *vos* instead of *tú* — a system called *voseo* — and ser is one of only two verbs (alongside *ir*) that breaks the regular voseo pattern. Most verbs form their voseo present by swapping a final "-r" for "-s" and shifting the stress to the last syllable, but ser\'s voseo present is simply *vos sos*, not a predictable variation on *tú eres*.',
					'In Rioplatense Spanish — the dialect spoken around the Río de la Plata basin, covering Argentina and Uruguay — *voseo* isn\'t a casual regionalism confined to friends; it\'s the everyday standard, used in schools, advertising, and television. A learner who only knows *tú eres* will still be understood there, but *vos sos* is what they\'ll actually hear.',
				],
			},
		],
		faq: [
			{
				question: 'Why don\'t "soy" and "sería" look like forms of the same verb?',
				answer: 'Because historically they aren\'t, quite. Ser is a suppletive verb: its present-tense forms (soy, eres, es...) descend from the Latin verb esse ("to be"), while most of its other forms — including the infinitive ser itself — descend from a different Latin verb, sedere ("to sit"). Two verbs merged into one paradigm over the course of Spanish\'s history.',
			},
			{
				question: 'Is the preterite of "ser" the same as the preterite of "ir"?',
				answer: 'Yes, exactly the same: fui, fuiste, fue, fuimos, fuisteis, fueron serves as the preterite for both ser ("to be") and ir ("to go"). Only context tells you which verb is meant — "fui a la tienda" (I went to the store) versus "fui estudiante" (I was a student).',
			},
			{
				question: 'Why does "ser" have only 5 imperative forms instead of 6?',
				answer: 'Like every Spanish verb, ser has no "yo" (I) form in the imperative, because commands are given to someone else, not to yourself. That leaves five: tú, usted, nosotros, vosotros, and ustedes.',
			},
			{
				question: 'Where do the forms in this table come from?',
				answer: 'They\'re generated from a hand-verified data table (see the source note under the conjugation table below), checked against Wiktionary\'s Spanish conjugation entry for ser and cross-checked against a second independent source, not generated from memory. The generator and its tests are open in the site\'s repository for anyone who wants to check the work.',
			},
		],
		sources: [
			{ label: 'Wiktionary — Spanish conjugation of "ser"', url: 'https://en.wiktionary.org/wiki/ser' },
			{ label: 'Spanish Linguist — "Why ser and ir are so irregular"', url: 'https://spanishlinguist.us/2017/02/why-ser-and-ir-are-so-irregular/' },
			{ label: 'Wikipedia — "Rioplatense Spanish" (voseo)', url: 'https://en.wikipedia.org/wiki/Rioplatense_Spanish' },
		],
		conjugation: {
			verb: 'ser',
			language: 'Spanish',
			translation: 'to be',
			regularity: 'irregular',
			tenses: [
				{
					tense: 'Present',
					forms: [
						{ pronoun: 'yo', form: 'soy' },
						{ pronoun: 'tú', form: 'eres' },
						{ pronoun: 'él/ella/usted', form: 'es' },
						{ pronoun: 'nosotros', form: 'somos' },
						{ pronoun: 'vosotros', form: 'sois' },
						{ pronoun: 'ellos/ellas/ustedes', form: 'son' },
					],
				},
				{
					tense: 'Preterite',
					forms: [
						{ pronoun: 'yo', form: 'fui' },
						{ pronoun: 'tú', form: 'fuiste' },
						{ pronoun: 'él/ella/usted', form: 'fue' },
						{ pronoun: 'nosotros', form: 'fuimos' },
						{ pronoun: 'vosotros', form: 'fuisteis' },
						{ pronoun: 'ellos/ellas/ustedes', form: 'fueron' },
					],
				},
				{
					tense: 'Imperfect',
					forms: [
						{ pronoun: 'yo', form: 'era' },
						{ pronoun: 'tú', form: 'eras' },
						{ pronoun: 'él/ella/usted', form: 'era' },
						{ pronoun: 'nosotros', form: 'éramos' },
						{ pronoun: 'vosotros', form: 'erais' },
						{ pronoun: 'ellos/ellas/ustedes', form: 'eran' },
					],
				},
				{
					tense: 'Future',
					forms: [
						{ pronoun: 'yo', form: 'seré' },
						{ pronoun: 'tú', form: 'serás' },
						{ pronoun: 'él/ella/usted', form: 'será' },
						{ pronoun: 'nosotros', form: 'seremos' },
						{ pronoun: 'vosotros', form: 'seréis' },
						{ pronoun: 'ellos/ellas/ustedes', form: 'serán' },
					],
				},
				{
					tense: 'Conditional',
					forms: [
						{ pronoun: 'yo', form: 'sería' },
						{ pronoun: 'tú', form: 'serías' },
						{ pronoun: 'él/ella/usted', form: 'sería' },
						{ pronoun: 'nosotros', form: 'seríamos' },
						{ pronoun: 'vosotros', form: 'seríais' },
						{ pronoun: 'ellos/ellas/ustedes', form: 'serían' },
					],
				},
				{
					tense: 'Subjunctive (present)',
					forms: [
						{ pronoun: 'yo', form: 'sea' },
						{ pronoun: 'tú', form: 'seas' },
						{ pronoun: 'él/ella/usted', form: 'sea' },
						{ pronoun: 'nosotros', form: 'seamos' },
						{ pronoun: 'vosotros', form: 'seáis' },
						{ pronoun: 'ellos/ellas/ustedes', form: 'sean' },
					],
				},
				{
					tense: 'Imperative (affirmative)',
					forms: [
						{ pronoun: 'tú', form: 'sé' },
						{ pronoun: 'usted', form: 'sea' },
						{ pronoun: 'nosotros', form: 'seamos' },
						{ pronoun: 'vosotros', form: 'sed' },
						{ pronoun: 'ustedes', form: 'sean' },
					],
				},
			],
			source: {
				label: 'Wiktionary — Spanish conjugation of "ser"',
				url: 'https://en.wiktionary.org/wiki/ser',
				note: 'Cross-checked against ellaverbs.com for imperfect/future forms, fetched 2026-08-03',
			},
		},
	},
	{
		slug: 'saber-vs-conocer',
		category: 'Grammar',
		title: 'Saber vs. Conocer: Spanish Has Two Verbs for "To Know"',
		description: 'English "to know" covers facts and people alike. Spanish splits it in two, and the split gets stricter, not looser, in the past tense.',
		published: '2026-08-04',
		updated: '2026-08-04',
		coreSummary: 'Saber is for facts, information, and learned skills (sé su número, sé nadar); conocer is for familiarity with people, places, and things (conozco a Ana, conozco Lima). The two verbs are not interchangeable, and the distinction gets sharper rather than fuzzier in the preterite: supe means "I found out," while conocí means "I met," a genuine change in meaning, not just tense.',
		language: 'Spanish',
		sections: [
			{
				heading: 'One English verb, two Spanish jobs',
				body: [
					'English "to know" stretches to cover two very different mental acts: knowing that something is true (*I know his phone number*), and being acquainted with someone or something (*I know his sister*). Spanish keeps those apart with two separate verbs, *saber* and *conocer*, and, unlike some pairs where the wrong choice is just an accent mistake, using the wrong one here produces a sentence a native speaker will notice immediately, because it claims something different than what you meant.',
					'The quickest sorting test: if you could rephrase the English sentence with "know how to," "know that," or "know a fact about," reach for *saber*. If you could rephrase it with "am familiar with" or "have met," reach for *conocer*. That test holds for almost every case; the exceptions are worth knowing on their own, and they show up further down.',
				],
			},
			{
				heading: 'Saber: facts, information, and how to do things',
				body: [
					'**Facts and information.** *Sé que el tren sale a las ocho.* (I know the train leaves at eight.) *No sé su número.* (I don\'t know his number.) *Saber* takes a fact, a piece of data, or a *que*-clause as its object, something you could, in principle, write down.',
					'**Skills, with an infinitive.** *Sé nadar. Sé tocar el piano. Sé hablar español.* (I know how to swim. I know how to play piano. I know how to speak Spanish.) This is the construction English speakers most often get wrong by reaching for *conocer* instead, because "I know how to" sounds closer to "familiarity" in English than it does in Spanish grammar.',
					'*Saber* and *poder* both get translated as "can" in English, and that overlap causes a second, separate mix-up. *Sé nadar* claims a skill: you learned to swim at some point and haven\'t forgotten how. *Puedo nadar* claims present ability, for reasons that have nothing to do with skill: the pool is open, nobody\'s stopping you, your arm isn\'t in a cast. A strong swimmer with a broken arm can honestly say *sé nadar, pero no puedo nadar ahora* ("I know how to swim, but I can\'t swim right now") without any contradiction.',
					'*Saber* is also one of the genuinely irregular verbs in Spanish rather than just an orthographic one: the *yo* form is *sé* (not *sabo*), the preterite stem is *sup-* (*supe, supiste, supo...*), and the future is built on *sabr-* (*sabré*) rather than the infinitive stem. None of those follow a predictable spelling rule the way *conocer*\'s does. They have to be learned as their own forms.',
				],
			},
			{
				heading: 'Conocer: familiarity with people, places, and things',
				body: [
					'**People.** *Conozco a Ana desde hace diez años.* (I\'ve known Ana for ten years.) Note the *a*: when the direct object of *conocer* is a specific person, Spanish requires the "personal a" before it, so it\'s *conozco a Ana*, never *conozco Ana*. Leaving it out is one of the most common non-native errors with this verb, distinct from the saber/conocer choice itself.',
					'**Places.** *Conozco Lima, pero nunca he estado en Cusco.* (I know Lima, but I\'ve never been to Cusco.) Here *conocer* means "have been to / am familiar with," which is why it doesn\'t take the personal *a*: a city isn\'t a person.',
					'**Things: books, films, ideas.** *Conozco esa novela; la leí el año pasado.* (I know that novel; I read it last year.) You aren\'t reciting facts about the novel here, you\'re claiming acquaintance with it as a whole, and that\'s what puts it on *conocer*\'s side rather than *saber*\'s.',
					'*Conocer* also has a common reflexive form, *conocerse*, and it splits into two different meanings depending on who\'s doing the knowing. *Nos conocimos en la universidad* means "We met each other in college," the moment a mutual acquaintance began. *Me conozco bien* means "I know myself well," turning the same reflexive back on the speaker rather than between two people. Only the context (a plural subject meeting someone else, versus a subject examining themselves) tells you which reading applies.',
					'*Conocer*\'s *yo* form is *conozco*, not *conoco*, but that\'s a spelling adjustment shared by a whole family of Spanish verbs ending in *-acer*, *-ecer*, *-ocer*, and *-ucir* (*parecer* → *parezco*, *conducir* → *conduzco*), not an irregularity unique to this verb the way *saber*\'s forms are.',
				],
				image: {
					src: '/images/saber-vs-conocer-diagram.svg',
					alt: 'Two-column comparison diagram: SABER covers facts and information, skills with an infinitive, the preterite meaning "found out," the idiom saber a ("taste like"), and a genuinely irregular yo form; CONOCER covers people, places, and familiarity with things, the preterite meaning "met," the personal a requirement before a person, and a yo form that is only a spelling adjustment.',
				},
			},
			{
				heading: 'Where the split gets sharper: the preterite',
				body: [
					'Most saber/conocer explanations stop at "facts vs. people," but the distinction actually tightens rather than loosens once you move into the preterite. In the preterite, *saber* and *conocer* do more than change endings: each one names a different kind of event.',
					'*Supe que María se casó.* Not "I knew that María got married" but "**I found out** that María got married": the preterite marks the moment the fact entered your head, not an ongoing state of possessing it. *Conocí a Ana en la fiesta.* Not "I knew Ana at the party" but "**I met** Ana at the party": the moment acquaintance began, not a state of already knowing her.',
					'This isn\'t a quirk unique to these two verbs. *Saber* and *conocer* belong to a small group of Spanish verbs, alongside *poder* ("was able to" becomes "managed to") and *querer* ("wanted to" becomes "tried to," in the affirmative, or "refused to" in the negative), where the preterite reports the specific instant a state began or resolved rather than simply placing a known state in the past. Learners who\'ve already sorted out the [broader preterite-versus-imperfect split](/preterite-vs-imperfect/) still trip on this group specifically, because the meaning shift is larger than "completed vs. ongoing." It\'s closer to two different English verbs mapping onto the same Spanish root.',
				],
			},
			{
				heading: 'Two more places they aren\'t quite parallel',
				body: [
					'**"Saber a" means "to taste like," not "to know."** *Esto sabe a limón.* (This tastes like lemon.) It\'s an idiomatic extension of *saber*\'s "have knowledge of" sense (you could think of it as the dish "knowing of" lemon), but it has to be memorized as its own construction rather than derived from the facts-vs-people rule.',
					'**"Conocer de" exists, but "saber de" is usually the better choice.** Spanish speakers sometimes say *conoce de carpintería* under the influence of *saber*, but the more standard and preferred phrasing is *sabe de carpintería* ("he knows about carpentry") or, for a specific instance, *sabía de casos así* ("I knew of cases like that") over *conocía de casos así*. If you\'re choosing between the two for a "know about X" construction, *saber de* is the safer default.',
					'One more contrast worth having next to this one: [ser and estar](/ser-vs-estar/) split English "to be" the way saber/conocer splits "to know," and the underlying move for both pairs is the same: stop translating the English word, and ask what kind of claim the sentence is actually making.',
				],
			},
			{
				heading: 'Three common mistakes, corrected',
				body: [
					'Seeing the wrong choice next to the right one tends to stick better than the rule alone. Three mix-ups account for most of the errors English speakers make with this pair.',
					'*Yo conozco que ella vive en Lima* is wrong; *yo sé que ella vive en Lima* is right. A fact introduced by *que* always takes *saber*, even though *conozco* can feel like the safer, more general-sounding verb.',
					'*Yo sé a tu profesor* is wrong; *yo conozco a tu profesor* is right. A person always takes *conocer*, and the personal *a* travels with *conocer*, never with *saber*.',
					'*Sé Madrid muy bien* is wrong; *conozco Madrid muy bien* is right. A place is a matter of familiarity, something you\'ve been to and walked around in, not information you could recite, so it stays on *conocer*\'s side even though "I know Madrid well" sounds like a fact in English.',
				],
			},
		],
		faq: [
			{
				question: 'Do you use saber or conocer for "I know how to swim" in Spanish?',
				answer: '*Sé nadar*, with *saber*. Any "know how to [verb]" construction (swimming, cooking, playing an instrument) uses *saber* plus an infinitive, never *conocer*. *Conocer* can\'t take an infinitive as its object at all.',
			},
			{
				question: 'Why does "conocí a Ana" mean "I met Ana" instead of "I knew Ana"?',
				answer: 'In the preterite, *conocer* reports the moment acquaintance began rather than an ongoing state of familiarity, so *conocí a Ana en la fiesta* means "I met Ana at the party." To describe an ongoing state of already knowing her in the past, Spanish switches to the imperfect: *conocía a Ana desde la universidad* ("I knew/had known Ana since college").',
			},
			{
				question: 'Do you need the personal "a" with both saber and conocer?',
				answer: 'No — only *conocer* triggers it, and only when the direct object is a specific person: *conozco a Ana*. *Saber* never takes the personal *a*, because its object is a fact, a skill, or a *que*-clause, never a person: *sé que Ana llegó*, not *sé a que Ana llegó*.',
			},
			{
				question: 'Is "saber a" ever used the way English uses "to know"?',
				answer: 'No — *saber a* is an idiom that means "to taste like" (*esto sabe a canela*, "this tastes like cinnamon"), unrelated to the facts-vs-familiarity distinction covered above. It has to be learned as its own fixed expression rather than derived from either of saber\'s main uses.',
			},
		],
		sources: [
			{ label: 'Real Academia Española — Diccionario de la lengua española: "saber"', url: 'https://dle.rae.es/saber' },
			{ label: 'Real Academia Española — Diccionario panhispánico de dudas: "conocer, conocerse"', url: 'https://www.rae.es/dpd/conocer' },
			{ label: 'CliffsNotes — "Verbs That Change Meaning in the Preterite"', url: 'https://www.cliffsnotes.com/study-guides/spanish/spanish-i/narration-in-the-past/verbs-that-change-meaning-in-the-preterite' },
		],
	},
];
